### (GraphQL API: sample requests to play with IntelliJ IDEA HTTP client)

### get some informations about a specific profile
POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Basic ROOT woot

{
    "query": "{ userById (id: 1) { id, username, nickname, authorities, version, userSnapshots { username, nickname, version, creationDate } } }"
}

### get some informations about my profile
POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Basic ROOT woot

{
    "query": "{ myUser { id, username, nickname, authorities, version, userSnapshots { username, nickname, version, creationDate } } }"
}

### update my nickname
POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Basic ROOT woot

{
    "query": "mutation { setMyNickname (nickname: \"foo bar\") { id, username, nickname, version } }"
}

### reset my nickname to null
POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Basic ROOT woot

{
    "query": "mutation { setMyNickname (nickname: null) { id, username, nickname, version } }"
}

###
