version: build-{build}.{branch}
clone_depth: 3

platform: x64
image: Visual Studio 2019

before_build:
  - set "JAVA_HOME=C:\Program Files\Java\jdk17"
  - set "PATH=C:\Program Files\Java\jdk17\bin;%PATH%"

build_script:
  - mvnw --no-transfer-progress clean package -DskipTests -B -U

test_script:
  - mvnw --no-transfer-progress verify -P ci -B -U

cache:
  - C:\Users\appveyor\.m2
