### DEV CONFIGURATION for local application with existing MariaDB db and in-memory cache ###  (warning: avoid tabs, indent with two spaces)

manon.cache.provider: ${MANON_DEV_CACHE_PROVIDER:embedded}

spring:
  datasource:
    username: ${MANON_DEV_SQL_USERNAME:root}
    password: ${MANON_DEV_SQL_PASSWORD:woot}
    url: ${MANON_DEV_SQL_JDBC_URL:jdbc:mariadb://localhost:3306/manon_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useMysqlMetadata=true}
  redis:
    database: ${MANON_DEV_REDIS_DATABASE:0}
    host: ${MANON_DEV_REDIS_HOST:""}
    port: ${MANON_DEV_REDIS_PORT:0}

management:
  health.redis.enabled: ${MANON_DEV_REDIS_MANAGEMENT:false}
