### DEV CONFIGURATION for local application with existing MariaDB ###  (warning: avoid tabs, indent with two spaces)

spring:
  datasource:
    username: root
    password: woot
    url: jdbc:mariadb://localhost:3306/manon_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useMysqlMetadata=true
