### DEV CONFIGURATION for local application
# In-memory HSQLDB db (schema is managed by Flyway)
# In-memory cache
### (warning: avoid tabs, indent with two spaces)

manon:
  batch:
    datasource:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      jdbcUrl: "jdbc:hsqldb:mem:manonbatch"
    flyway.location: "classpath:db/migration/hsqldb/batch"
  cache.provider: ${MANON_DEV_CACHE_PROVIDER:embedded}

spring:
  data:
    redis:
      database: ${MANON_DEV_REDIS_DATABASE:0}
      host: ${MANON_DEV_REDIS_HOST:""}
      port: ${MANON_DEV_REDIS_PORT:0}
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    jdbcUrl: "jdbc:hsqldb:mem:manon"
  flyway.locations: ["classpath:db/migration/hsqldb/main"]
  mail:
    host: ${MANON_DEV_MAIL_HOST:}
    port: ${MANON_DEV_MAIL_PORT:}
    username: ${MANON_DEV_MAIL_USERNAME:}
    password: ${MANON_DEV_MAIL_PASSWORD:}
    test-connection: ${MANON_DEV_MAIL_TEST_CONNECTION:false}

management:
  health:
    mail.enabled: ${MANON_DEV_MAIL_MANAGEMENT:false}
    redis.enabled: ${MANON_DEV_REDIS_MANAGEMENT:false}
