services:

  maria-test:
    container_name: maria-test
    image: mariadb:11.5.2 # see https://hub.docker.com/_/mariadb/
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: woot
      MYSQL_DATABASE: manon

  maria-batch-test:
    container_name: maria-batch-test
    image: mariadb:11.5.2 # see https://hub.docker.com/_/mariadb/
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: woot
      MYSQL_DATABASE: manon_batch

  redis-test:
    container_name: redis-test
    image: redis:7.4.1-alpine # see https://hub.docker.com/_/redis/
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
