package manon.model.user;

public enum FriendshipEventCode {
    
    YOU_SENT_FRIEND_REQUEST,
    YOU_ACCEPTED_FRIEND_REQUEST,
    YOU_REJECTED_FRIEND_REQUEST,
    YOU_CANCELED_FRIEND_REQUEST,
    YOU_REVOKED_FRIEND_REQUEST,
    
    TARGET_SENT_FRIEND_REQUEST,
    TARGET_ACCEPTED_FRIEND_REQUEST,
    TARGET_REJECTED_FRIEND_REQUEST,
    TARGET_CANCELED_FRIEND_REQUEST,
    TARGET_REVOKED_FRIEND_REQUEST
}
